### PR TITLE
OCPCLOUD-2189: Update to match K8s v1.28 dependencies

### PR DESCRIPTION
**Pull request by yanhua121**
Update the dependencies to match K8s v1.28.

### CODE REVIEW

**Comment by elmiko** [comment]
@yanhua121 similar to the cloud-provider update, is the e2e-nutanix failure here related to the change?

**Comment by elmiko** [comment]
adding the associated jira card

/retitle OCPCLOUD-2189: Update to match K8s v1.28 dependencies

**Comment by yanhua121** [comment]
> @yanhua121 similar to the cloud-provider update, is the e2e-nutanix failure here related to the change?

@elmiko I can reproduce the statefulset issue with the nutanix-csi installed in a local OCP 4.15 nightly build cluster without apply the PR changes. I suspect the issue is related to nutanix-csi driver/provisioner. I am reporting this issue to our nutanix-csi team. So it means that the e2e-nutanix statefulset failures are not caused by this PR.

**Comment by elmiko** [comment]
thanks @yanhua121 , i think it's ok for us to merge this since the issue appears to be on the storage side.

/approve
/lgtm

**Pull request merged**
