### PR TITLE
OCPCLOUD-2053: Update dependencies to K8s 1.27

### PR DESCRIPTION
**Pull request by damdo**
This updates the dependencies to the latest versions to support K8s 1.27.

TODO: update reference to machine-api-operator once https://github.com/openshift/machine-api-operator/pull/1142 merges

### CODE REVIEW

**Comment by damdo** [comment]
/hold
until https://github.com/openshift/machine-api-operator/pull/1142 merges

**Comment by damdo** [comment]
Bootstrap failed:

/retest

**Comment by JoelSpeed** [comment]
/override ci/prow/e2e-nutanix-operator 

The tests passed barring the cluster autoscaler balance similar nodes test. This test needs to be taught about platform specific labels and as such, isn't working on Nutanix yet. I'm confident this PR is ok without that single test pass, we will make sure to update the E2E to account for Nutanix for future PRs

CC @elmiko

**Comment by JoelSpeed** [comment]
/hold cancel

Stale hold

**Pull request merged**
