### PR TITLE
Add main code from Nutanix

### PR DESCRIPTION
**Pull request by elmiko**
This PR brings in the history from the https://github.com/nutanix-cloud-native/machine-api-provider-nutanix repo main branch.

### CODE REVIEW

**Comment by JoelSpeed** [comment]
Are these commit sha's the same as the sha's from the original repo? Looks like this may be rebased/ammended? Is there a way we can merge the original commits without rebasing? Would that make future rebases on the upstream repo easier? (I assume we are having an upstream?

**Comment by elmiko** [comment]
these are not the same commit hashes, i have rebased on top of the repo here. i don't think this will be an issue though, Nutanix have agreed that this will be the source of truth and they will make a fork from this repo once we have it setup.

**Comment by elmiko** [comment]
>  (I assume we are having an upstream?

i don't think we agreed to that, but if we want to set this up so that they can push changes to their repo and then we bring them here by bot then i still think we are ok if they fork from here.

**Review by Fedosin — APPROVED** [review]
/approve
/lgtm

**Comment by elmiko** [comment]
@Fedosin i think we will need Joel to manually merge this one

**Pull request merged**
