### PR TITLE
OCPBUGS-27390: IPI install fails on Nutanix when using DHCP

### PR DESCRIPTION
**Pull request by yanhua121**
OCPBUGS-27390: IPI install fails with etcdInsufficientMembers on Nutanix when using DHCP network

Manually tested the fix  in-lab with the DHCP subnet.

This bug fix needs back-port to 4.15, 4.14, 4.13, 4.12 release branches. The customer reported this issue OCPBUGS-27390 is using 4.14.9.

### CODE REVIEW

**Comment by yanhua121** [comment]
@elmiko @JoelSpeed Can you review and see if it is approvable?

**Comment by JoelSpeed** [comment]
@yanhua121 Any idea why CI is so red? Do you think we can try to get CI working to prove this works?

**Comment by yanhua121** [comment]
> @yanhua121 Any idea why CI is so red? Do you think we can try to get CI working to prove this works?

@JoelSpeed See the slack discussion on the regression PR that caused the e2e-nutanix ci jobs failure. https://redhat-internal.slack.com/archives/C0211848DBN/p1707924312733509.

**Review by JoelSpeed — COMMENTED** [review]
/approve
/lgtm

**Pull request merged**
